// This file is auto-generated. Do not modify manually.
// Generated by AnimatorParameterEnumGenerator
// Generated on: 2/6/2026 12:35:47 AM
// Source: AC_Base

namespace Game.Animation
{
    public static class ACBase
    {
        public const int Walk = 765711723;
        public const int Death = 646380074;
        public const int Attack = 1080829965;
    }
}
