// This file is auto-generated. Do not modify manually.
// Generated by AnimatorParameterEnumGenerator
// Generated on: 2/5/2026 8:38:06 PM
// Source: AC_Base

using System.Collections.Generic;

namespace Game.Animation
{
    public enum ACBase
    {
        None = 0,
        Attack = 1,
        Walk = 2,
        Death = 3,
    }

    public static class ACBaseExtensions
    {
        private static readonly Dictionary<ACBase, string> ParameterNames = new Dictionary<ACBase, string>
        {
            { ACBase.None, string.Empty },
            { ACBase.Attack, "Attack" },
            { ACBase.Walk, "Walk" },
            { ACBase.Death, "Death" },
        };

        private static readonly Dictionary<string, ACBase> NameToEnum = new Dictionary<string, ACBase>
        {
            { string.Empty, ACBase.None },
            { "Attack", ACBase.Attack },
            { "Walk", ACBase.Walk },
            { "Death", ACBase.Death },
        };

        public static string ToParameterName(this ACBase parameter)
        {
            return ParameterNames.TryGetValue(parameter, out string name) ? name : string.Empty;
        }

        public static ACBase FromParameterName(string parameterName)
        {
            return NameToEnum.TryGetValue(parameterName, out ACBase parameter) ? parameter : ACBase.None;
        }
    }
}
