// This file is auto-generated. Do not modify manually.
// Generated by AnimationEventEnumGenerator
// Generated on: 2/4/2026 5:38:51 PM

using System.Collections.Generic;

namespace Game.Animation
{
    public enum AnimationEventType
    {
        None = 0,
        DealDamage = 1,
        FootL = 2,
        FootR = 3,
        Hit = 4,
        SpawnProjectile = 5,
    }

    public static class AnimationEventTypeExtensions
    {
        private static readonly Dictionary<AnimationEventType, string> EventNames = new Dictionary<AnimationEventType, string>
        {
            { AnimationEventType.None, string.Empty },
            { AnimationEventType.DealDamage, "DealDamage" },
            { AnimationEventType.FootL, "FootL" },
            { AnimationEventType.FootR, "FootR" },
            { AnimationEventType.Hit, "Hit" },
            { AnimationEventType.SpawnProjectile, "SpawnProjectile" },
        };

        private static readonly Dictionary<string, AnimationEventType> NameToEnum = new Dictionary<string, AnimationEventType>
        {
            { string.Empty, AnimationEventType.None },
            { "DealDamage", AnimationEventType.DealDamage },
            { "FootL", AnimationEventType.FootL },
            { "FootR", AnimationEventType.FootR },
            { "Hit", AnimationEventType.Hit },
            { "SpawnProjectile", AnimationEventType.SpawnProjectile },
        };

        /// <summary>
        /// Получить строковое имя события для использования в Animation Event
        /// </summary>
        public static string ToEventName(this AnimationEventType eventType)
        {
            return EventNames.TryGetValue(eventType, out string name) ? name : string.Empty;
        }

        /// <summary>
        /// Получить enum из строкового имени события
        /// </summary>
        public static AnimationEventType FromEventName(string eventName)
        {
            return NameToEnum.TryGetValue(eventName, out AnimationEventType eventType) ? eventType : AnimationEventType.None;
        }
    }
}
