using UnityEngine;
using UnityEditor;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

public class AnimationEventEnumGenerator : EditorWindow
{
    private string enumName = "AnimationEventType";
    private string outputPath = "Assets/Game/Scripts/CodeGen";
    private string namespaceString = "Game.Animation";
    private bool includeNamespace = true;
    private Vector2 scrollPosition;
    private List<string> foundEvents = new List<string>();
    
    [MenuItem("Tools/Generate Animation Events Enum")]
    public static void ShowWindow()
    {
        GetWindow<AnimationEventEnumGenerator>("Animation Events Generator");
    }

    private void OnGUI()
    {
        GUILayout.Label("Animation Event Enum Generator", EditorStyles.boldLabel);
        EditorGUILayout.Space();

        enumName = EditorGUILayout.TextField("Enum Name:", enumName);
        outputPath = EditorGUILayout.TextField("Output Path:", outputPath);
        
        includeNamespace = EditorGUILayout.Toggle("Include Namespace:", includeNamespace);
        if (includeNamespace)
        {
            namespaceString = EditorGUILayout.TextField("Namespace:", namespaceString);
        }

        EditorGUILayout.Space();

        if (GUILayout.Button("Scan Project for Animation Events", GUILayout.Height(30)))
        {
            ScanAnimationEvents();
        }

        EditorGUILayout.Space();

        if (foundEvents.Count > 0)
        {
            GUILayout.Label($"Found {foundEvents.Count} unique events:", EditorStyles.boldLabel);
            
            scrollPosition = EditorGUILayout.BeginScrollView(scrollPosition, GUILayout.Height(200));
            foreach (var eventName in foundEvents)
            {
                EditorGUILayout.LabelField("• " + eventName);
            }
            EditorGUILayout.EndScrollView();

            EditorGUILayout.Space();

            if (GUILayout.Button("Generate Enum File", GUILayout.Height(30)))
            {
                GenerateEnumFile();
            }
        }
    }

    private void ScanAnimationEvents()
    {
        foundEvents.Clear();
        HashSet<string> eventNames = new HashSet<string>();

        // Находим все AnimationClip в проекте
        string[] guids = AssetDatabase.FindAssets("t:AnimationClip");
        
        EditorUtility.DisplayProgressBar("Scanning Animations", "Processing animation clips...", 0);

        for (int i = 0; i < guids.Length; i++)
        {
            string path = AssetDatabase.GUIDToAssetPath(guids[i]);
            AnimationClip clip = AssetDatabase.LoadAssetAtPath<AnimationClip>(path);

            if (clip != null)
            {
                AnimationEvent[] events = AnimationUtility.GetAnimationEvents(clip);
                
                foreach (var animEvent in events)
                {
                    if (!string.IsNullOrEmpty(animEvent.functionName))
                    {
                        eventNames.Add(animEvent.functionName);
                    }
                }
            }

            EditorUtility.DisplayProgressBar("Scanning Animations", 
                $"Processing {i + 1}/{guids.Length}: {Path.GetFileName(path)}", 
                (float)(i + 1) / guids.Length);
        }

        EditorUtility.ClearProgressBar();

        foundEvents = eventNames.OrderBy(x => x).ToList();
        
        Debug.Log($"Animation Event Scan Complete! Found {foundEvents.Count} unique events.");
    }

    private void GenerateEnumFile()
    {
        if (foundEvents.Count == 0)
        {
            EditorUtility.DisplayDialog("No Events", "No animation events found. Please scan first.", "OK");
            return;
        }

        // Создаём директорию если не существует
        if (!Directory.Exists(outputPath))
        {
            Directory.CreateDirectory(outputPath);
        }

        StringBuilder sb = new StringBuilder();
        
        // Заголовок файла
        sb.AppendLine("// This file is auto-generated. Do not modify manually.");
        sb.AppendLine("// Generated by AnimationEventEnumGenerator");
        sb.AppendLine($"// Generated on: {System.DateTime.Now}");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        // Namespace
        if (includeNamespace && !string.IsNullOrEmpty(namespaceString))
        {
            sb.AppendLine($"namespace {namespaceString}");
            sb.AppendLine("{");
        }

        string indent = includeNamespace ? "    " : "";

        // Enum
        sb.AppendLine($"{indent}public enum {enumName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    None = 0,");
        
        for (int i = 0; i < foundEvents.Count; i++)
        {
            string eventName = SanitizeEnumName(foundEvents[i]);
            sb.AppendLine($"{indent}    {eventName} = {i + 1},");
        }
        
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // Helper класс для маппинга
        sb.AppendLine($"{indent}public static class {enumName}Extensions");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    private static readonly Dictionary<{enumName}, string> EventNames = new Dictionary<{enumName}, string>");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        {{ {enumName}.None, string.Empty }},");
        
        for (int i = 0; i < foundEvents.Count; i++)
        {
            string enumValue = SanitizeEnumName(foundEvents[i]);
            string originalName = foundEvents[i];
            sb.AppendLine($"{indent}        {{ {enumName}.{enumValue}, \"{originalName}\" }},");
        }
        
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine();
        sb.AppendLine($"{indent}    private static readonly Dictionary<string, {enumName}> NameToEnum = new Dictionary<string, {enumName}>");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        {{ string.Empty, {enumName}.None }},");
        
        for (int i = 0; i < foundEvents.Count; i++)
        {
            string enumValue = SanitizeEnumName(foundEvents[i]);
            string originalName = foundEvents[i];
            sb.AppendLine($"{indent}        {{ \"{originalName}\", {enumName}.{enumValue} }},");
        }
        
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine();
        
        // Методы расширения
        sb.AppendLine($"{indent}    /// <summary>");
        sb.AppendLine($"{indent}    /// Получить строковое имя события для использования в Animation Event");
        sb.AppendLine($"{indent}    /// </summary>");
        sb.AppendLine($"{indent}    public static string ToEventName(this {enumName} eventType)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return EventNames.TryGetValue(eventType, out string name) ? name : string.Empty;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        
        sb.AppendLine($"{indent}    /// <summary>");
        sb.AppendLine($"{indent}    /// Получить enum из строкового имени события");
        sb.AppendLine($"{indent}    /// </summary>");
        sb.AppendLine($"{indent}    public static {enumName} FromEventName(string eventName)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return NameToEnum.TryGetValue(eventName, out {enumName} eventType) ? eventType : {enumName}.None;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");

        // Закрываем namespace
        if (includeNamespace && !string.IsNullOrEmpty(namespaceString))
        {
            sb.AppendLine("}");
        }

        // Сохраняем файл
        string fullPath = Path.Combine(outputPath, $"{enumName}.cs");
        File.WriteAllText(fullPath, sb.ToString());
        
        AssetDatabase.Refresh();
        
        EditorUtility.DisplayDialog("Success", 
            $"Enum file generated successfully!\n\nPath: {fullPath}\nEvents: {foundEvents.Count}", 
            "OK");
        
        // Открываем файл
        UnityEditorInternal.InternalEditorUtility.OpenFileAtLineExternal(fullPath, 1);
    }

    private string SanitizeEnumName(string name)
    {
        // Удаляем недопустимые символы для имени enum
        StringBuilder sb = new StringBuilder();
        
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
            {
                sb.Append(c);
            }
            else
            {
                sb.Append('_');
            }
        }

        string result = sb.ToString();
        
        // Если начинается с цифры, добавляем префикс
        if (char.IsDigit(result[0]))
        {
            result = "Event_" + result;
        }

        return result;
    }
}