using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

public class AnimatorParameterEnumGenerator : EditorWindow
{
    private AnimatorController selectedController;
    private string enumName = "AnimatorParameter";
    private string outputPath = "Assets/Game/Scripts/CodeGen";
    private string namespaceString = "Game.Animation";
    private bool includeNamespace = true;
    private Vector2 scrollPosition;
    private List<AnimatorControllerParameter> foundParameters = new List<AnimatorControllerParameter>();
    
    [MenuItem("Tools/Generate Animator Parameters Enum")]
    public static void ShowWindow()
    {
        GetWindow<AnimatorParameterEnumGenerator>("Animator Parameters Generator");
    }

    private void OnGUI()
    {
        GUILayout.Label("Animator Parameter Enum Generator", EditorStyles.boldLabel);
        EditorGUILayout.Space();

        selectedController = EditorGUILayout.ObjectField("Animator Controller:", selectedController, typeof(AnimatorController), false) as AnimatorController;
        
        EditorGUILayout.Space();
        
        enumName = EditorGUILayout.TextField("Enum Name:", enumName);
        outputPath = EditorGUILayout.TextField("Output Path:", outputPath);
        
        includeNamespace = EditorGUILayout.Toggle("Include Namespace:", includeNamespace);
        if (includeNamespace)
        {
            namespaceString = EditorGUILayout.TextField("Namespace:", namespaceString);
        }

        EditorGUILayout.Space();

        if (GUILayout.Button("Scan Controller Parameters", GUILayout.Height(30)))
        {
            ScanParameters();
        }

        EditorGUILayout.Space();

        if (foundParameters.Count > 0)
        {
            GUILayout.Label($"Found {foundParameters.Count} parameters:", EditorStyles.boldLabel);
            
            scrollPosition = EditorGUILayout.BeginScrollView(scrollPosition, GUILayout.Height(200));
            foreach (var param in foundParameters)
            {
                EditorGUILayout.LabelField($"• {param.name} ({param.type})");
            }
            EditorGUILayout.EndScrollView();

            EditorGUILayout.Space();

            if (GUILayout.Button("Generate Enum File", GUILayout.Height(30)))
            {
                GenerateEnumFile();
            }
        }
    }

    private void ScanParameters()
    {
        foundParameters.Clear();

        if (selectedController == null)
        {
            EditorUtility.DisplayDialog("No Controller", "Please select an Animator Controller first.", "OK");
            return;
        }

        foundParameters = selectedController.parameters.ToList();
        
        Debug.Log($"Scan Complete! Found {foundParameters.Count} parameters in {selectedController.name}.");
    }

    private void GenerateEnumFile()
    {
        if (foundParameters.Count == 0)
        {
            EditorUtility.DisplayDialog("No Parameters", "No parameters found. Please scan first.", "OK");
            return;
        }

        if (!Directory.Exists(outputPath))
        {
            Directory.CreateDirectory(outputPath);
        }

        StringBuilder sb = new StringBuilder();
        
        sb.AppendLine("// This file is auto-generated. Do not modify manually.");
        sb.AppendLine("// Generated by AnimatorParameterEnumGenerator");
        sb.AppendLine($"// Generated on: {System.DateTime.Now}");
        sb.AppendLine($"// Source: {selectedController.name}");
        sb.AppendLine();

        if (includeNamespace && !string.IsNullOrEmpty(namespaceString))
        {
            sb.AppendLine($"namespace {namespaceString}");
            sb.AppendLine("{");
        }

        string indent = includeNamespace ? "    " : "";

        sb.AppendLine($"{indent}public static class {enumName}");
        sb.AppendLine($"{indent}{{");
        
        for (int i = 0; i < foundParameters.Count; i++)
        {
            string paramName = SanitizeEnumName(foundParameters[i].name);
            int hash = Animator.StringToHash(foundParameters[i].name);
            sb.AppendLine($"{indent}    public const int {paramName} = {hash};");
        }
        
        sb.AppendLine($"{indent}}}");

        if (includeNamespace && !string.IsNullOrEmpty(namespaceString))
        {
            sb.AppendLine("}");
        }

        string fullPath = Path.Combine(outputPath, $"{enumName}.cs");
        File.WriteAllText(fullPath, sb.ToString());
        
        AssetDatabase.Refresh();
        
        EditorUtility.DisplayDialog("Success", 
            $"Enum file generated successfully!\n\nPath: {fullPath}\nParameters: {foundParameters.Count}", 
            "OK");
        
        UnityEditorInternal.InternalEditorUtility.OpenFileAtLineExternal(fullPath, 1);
    }

    private string SanitizeEnumName(string name)
    {
        StringBuilder sb = new StringBuilder();
        
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
            {
                sb.Append(c);
            }
            else
            {
                sb.Append('_');
            }
        }

        string result = sb.ToString();
        
        if (char.IsDigit(result[0]))
        {
            result = "Param_" + result;
        }

        return result;
    }
}